### ISSUE TITLE
词汇表订正

### ISSUE THREAD

**Issue by freeyao** [ShanghaiAdvancedTechSeminar/Publications#8]
[词汇表](https://github.com/ShanghaiAdvancedTechSeminar/Publications/blob/main/Bitcoin%20Glossary.md)中的 『交易』 均 改为『事务』。

**Comment by Stamp9** [comment]
> [词汇表](https://github.com/ShanghaiAdvancedTechSeminar/Publications/blob/main/Bitcoin%20Glossary.md)中的 『交易』 均 改为『事务』。

是Trade的改为事务还是transaction改为事务？还是两者都改？

**Comment by freeyao** [comment]
transaction

Stamp9 ***@***.***> 于2021年3月30日周二 下午4:16写道：
